### ISSUE TITLE
Newbie problems

### ISSUE THREAD

**Issue by owenl013** [scfmod/FS22_MaterialProcessor#2]
Hey, I have some basic knowledge of fs modding but i really cant get the code working for the screener i've tried all of the machines from fs miner but i continuously get the lua error:

FS22_1_MaterialProcessor/scripts/processorTypes/SplitProcessorConfiguration.lua:63: Could not find any outputs: vehicle.materialProcessor.configurations.configuration(0).input

Now i have gotten most of all of the machines to work with terrafarm no problem hopefully you guys could help explain this one to me.

**Comment by scfmod** [comment]
Well in order for the processor to function you need to setup configuration(s) :)

https://github.com/scfmod/FS22_MaterialProcessor/blob/main/docs/PROCESSOR_SPLIT.md#configurations

**Comment by xAnarchyx** [comment]
Hey there, i have tried following the guide but, have not got it to work, currently trying to edit the trex crusher double belt,
the error i'm getting is 
Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
FarmingSimulator2022/mods/FS22_1_MaterialProcessor/scripts/processorTypes/SplitProcessorConfiguration.lua:63: Could not find any outputs: vehicle.materialProcessor.configurations.configuration(0).input

here following code i have tried to make 

<materialProcessor          
        type="split" needsToBeTurnedOn="true" needsToBePoweredOn="true" defaultCanDischargeToGround="false" canToggleDischargeToGround="true"canDischargeToGroundAnywhere="true" canDischargeToAnyObject="true">
        <configurations>
            
           <configuration name="Dirt Screening" litersPerSecond="500">
                <input fillType="DIRT" fillUnitIndex="3">
                    <ouput fillType="SEPARATED_MANURE" fillUnitIndex="4" ratio="0.3" />
                    <ouput fillType="GRADEDMULCH" fillUnitIndex="5" ratio="0.7" />
                </input>
            </configuration>
            
            <configuration name="Stone Crushing" litersPerSecond="500">
                <input fillType="CRUSHEDSTONE" fillUnitIndex="3">
                    <ouput fillType="RUBBLE" fillUnitIndex="4" ratio="0.3" />
                    <ouput fillType="DIRT" fillUnitIndex="5" ratio="0.7" />
                </input>
            </configuration>
            
        </configurations>
        <dischargeNodes>
            
                
            <node node="dischargeNodeFront" emptySpeed="1" fillUnitIndex="4" canDischargeToGround="true"  canStartDischargeAutomatically="true" canStartGroundDischargeAutomatically="true" unloadInfoIndex="1" >
                    <activationTrigger node="activationTriggerFront" />
                    <raycast useWorldNegYDirection="true" />
                    <info width="0.55" length="0.55" />
                <effects>
                       <effectNode effectNode="effectDischargeFront" materialType="unloading" fadeTime="0.2" alignXAxisToWorldY="true" extraDistance="0.2" />
                       <effectNode effectClass="MorphPositionEffect" effectNode="effectDischargeBeltFront" materialType="belt" fadeTime="1" speed="0.25" scrollLength="4" scrollSpeed="1.1" />
                       <effectNode effectNode="effectSmoke1Front" materialType="unloadingSmoke" fadeTime="0" />
              </effects>
            <dischargeStateSound template="augerBelt" pitchScale="0.7" volumeScale="1.4" fadeIn="0.2" fadeOut="1" innerRadius="1.0" outerRadius="40.0" />
                </node>
            
            
    
                <node node="dischargeNodeSideR" emptySpeed="1" fillUnitIndex="5" canDischargeToGround="true"  canStartDischargeAutomatically="true" canStartGroundDischargeAutomatically="true" unloadInfoIndex="2" >
                    <activationTrigger node="activationTriggerSide" />
                    <raycast useWorldNegYDirection="true" />
                    <info width="0.55" length="0.55" />
                    <effects>
                       <effectNode effectNode="effectDischargeSide" materialType="unloading" fadeTime="0.2" alignXAxisToWorldY="true" extraDistance="0.2" />
                       <effectNode effectClass="MorphPositionEffect" effectNode="effectDischargeBeltSide" materialType="belt" fadeTime="1" speed="0.25" scrollLength="4" scrollSpeed="1.1" />
                       <effectNode effectNode="effectSmoke1Side" materialType="unloadingSmoke" fadeTime="0" /><effectNode effectNode="effectSmokeCone" materialType="unloadingSmoke" fadeTime="0" />
                        <effectNode effectNode="effectCone" materialType="unloading" fadeTime="0" alignXAxisToWorldY="true" extraDistance="0.2" />
                       <effectNode effectClass="MorphPositionEffect" effectNode="effectMainBelt1" materialType="belt" fadeTime="1" speed="0.25" scrollLength="4" scrollSpeed="1.1" />
              </effects>
            <dischargeStateSound template="augerBelt" pitchScale="0.7" volumeScale="1.4" fadeIn="0.2" fadeOut="1" innerRadius="1.0" outerRadius="40.0" />
                </node>
                
        </dischargeNodes>        
    </materialProcessor>

**Comment by scfmod** [comment]
```<ouput ..``` should be ```<output ...```
Guess I had a typo in documentation, will fix that 😅
